import figma from '@figma/code-connect';
import React from 'react';

import { Button } from './Button';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Button,
  'https://www.figma.com/design/P4R6fxBCbRMz3ohoSfbt7X/Core-Components-Akamai-DS?node-id=19513%3A1430',
  {
    props: {
      // These props were automatically mapped based on your linked code:
      children: figma.string('Label'),
      disabled: figma.enum('State', {
        Disabled: true,
      }),
      size: figma.enum('Size', {
        Small: 'small',
        Large: 'large',
      }),
      startIcon: figma.instance('Icon'),
      endIcon: figma.instance('Icon'),
      // We could potentially get rid of these in Figma:
      // "rightIcon": figma.boolean('Right icon'),
      // "smallIcon": figma.instance('Small icon'),
      // "leftIcon": figma.boolean('Left icon'),
      buttonType: figma.enum('Type', {
        Primary: 'primary',
        Secondary: 'outlined',
        // No matching props could be found for these Figma properties:
        // "Link": "link",
        // "Launch": "launch",
        // "Tertiary": "tertiary"
      }),
      color: figma.enum('Type', {
        Danger: 'error',
      }),
    },
    example: (props) => (
      <Button
        buttonType={props.buttonType}
        color={props.color}
        disabled={props.disabled}
        endIcon={props.endIcon}
        size={props.size}
        startIcon={props.startIcon}
      >
        {props.children}
      </Button>
    ),
  },
);
